server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http//localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: clients
          uri: lb://clients
          predicates:
            - Path=/clients/**
          filters:
            - RewritePath=/clients/*, /
        - id: products
          uri: lb://product
          predicates:
            - Path=/product/**
        - id: movements
          uri: lb://movements
          predicates:
            - Path=/movements/**
    
